language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd inspection-report-client
  - npm install
  - npm test
  - npm run build
before_deploy:
  - cd build
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  site: https://inspetionreporttest30559.azurewebsites.net
  verbose: true