language: node_js
node_js: stable
sudo: required
dist: trusty
sctipt:
  - cd inspection-report-client
install:
  - npm install
script:
  - npm run test
  - npm run build
before_deploy:
  - cd build
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  site: https://inspetionreporttest30559.azurewebsites.net
  verbose: true