language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd inspection-report-app
  - npm install
  - npm test
  - npm run build
deploy:
  provider: azure_web_apps
  site: https://inspetionreporttest30559.azurewebsites.net
  on: master